#!/bin/bash

# This script belongs to Mackenzie Horgan

#Gathers variables from /etc/os-release if it exists on the system
source /etc/os-release
#Veriables used from above are:
#$PRETTY_NAME

###Variables###
#finds username of current user
myUsername="$USER"
#finds current date and time
currentDateTime="$(date)"
#finds name of the host machine
currentHostname="$(hostname)"
#displays the machine's current uptime
currentUptime="$(uptime)"
#runs lscpu, extracts line containing 'Model name:', and removes unimportant text
cpuInfo="$(lscpu | grep 'Model name:' | sed 's/Model name:                           //')"
#runs lshw, extracts the first instance of 'size', and removes unimportant text
ram="$(lshw | grep -m 1 size | sed 's/          size: //')"
#accesses /proc/cpuinfo, extracts the first instance of 'MHz', and only returns anything on the line containing numbers 0-9 and decimals
cpuSpeed="$(cat /proc/cpuinfo | grep -m 1 MHz | grep -o [0-9.]*)"
#runs lshw looking for display devices, extracts lines with 'vendor' and 'product', removes unimportant spaces, replaces 'vendor' and 'product' strings, removes new line
videoCard="$(sudo lshw -c display | grep -e 'vendor' -e 'product' | sed 's/       //' | sed 's/vendor/ Produced By/g' | sed 's/product://' | tr -d '\n')"

#########################################

#Report template
cat <<EOF

System Report generated by $myUsername, $currentDateTime
 
System Information
------------------
Hostname: $currentHostname
OS: $PRETTY_NAME
Uptime: $currentUptime
 
Hardware Information
--------------------
cpu: $cpuInfo
Speed: $cpuSpeed MHz
Ram: $ram
Disk(s): MAKE AND MODEL AND SIZE FOR ALL INSTALLED DISKS
Video Card: $videoCard
 
Network Information
-------------------
FQDN: FQDN
Host Address: IP ADDRESS FOR THE HOSTNAME
Gateway IP: GATEWAY ADDRESS
DNS Server: IP OF DNS SERVER
 
InterfaceName: MAKE AND MODEL OF NETWORK CARD
IP Address: IP Address in CIDR format
 
System Status
-------------
Users Logged In: USER,USER,USER...
Disk Space: FREE SPACE FOR LOCAL FILESYSTEMS IN FORMAT: /MOUNTPOINT N
Process Count: N
Load Averages: N, N, N
Memory Allocation: DATA FROM FREE
Listening Network Ports: N, N, N, ...
UFW Rules: DATA FROM UFW SHOW
EOF
