#!/bin/bash

# This script belongs to Mackenzie Horgan

#Gathers variables from /etc/os-release if it exists on the system
source /etc/os-release
#Veriables used from above are:
#$PRETTY_NAME

######Variables######
#finds username of current user
myUsername="$USER"
#finds current date and time
currentDateTime="$(date)"
#finds name of the host machine
currentHostname="$(hostname)"
#displays the machine's current uptime
currentUptime="$(uptime)"
#runs lscpu, extracts line containing 'Model name:', and removes unimportant text
cpuInfo="$(lscpu | grep 'Model name:' | sed 's/Model name:                           //')"
#runs lshw, extracts the first instance of 'size', and removes unimportant text
ram="$(lshw | grep -m 1 size | sed 's/          size: //')"
#accesses /proc/cpuinfo, extracts the first instance of 'MHz', and only returns anything on the line containing numbers 0-9 and decimals
cpuSpeed="$(cat /proc/cpuinfo | grep -m 1 MHz | grep -o [0-9.]*)"
#runs lshw looking for display devices, extracts lines with 'vendor' and 'product', removes unimportant spaces, replaces 'vendor' and 'product' strings, removes new line
videoCard="$(sudo lshw -c display | grep -e 'vendor' -e 'product' | sed 's/       //' | sed 's/vendor/    Produced By/g' | sed 's/product://' | tr -d '\n')"
#finds the machine's fqdn
getFQDN="$(hostname -f)"
#finds IP of the hostname
hostnameIP="$(hostname -I)"
#finds routing info, locates word 'default', gathers text of ip addresses, returns the first address (which is the default gateway)
defaultGateway="$(ip route | grep default | grep -o [0-9.]* | grep -m 1 [0-9.])"
#extracts 'nameserver' line from resolv.conf, removes unimportant text.
dnsIP="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //')"
#runs lshw looking for network devices, extracts lines with 'product' and 'vendor', removes unimportant spaces, replaces 'product' and 'vendor' strings, and removes the new line
nicInfo="$(sudo lshw -class network | grep -e 'product' -e 'vendor' | sed 's/       //' | sed 's/product://' | sed 's/vendor/    Produced By/g' | tr -d '\n')"
cidrIP="$(ip r | grep -o [0-9./]* | grep '/')"
#display logged in users
usersLoggedIn="$(users)"
#displays process number
processNum="$(echo $$)"
#runs uptime, exatracts any text matching X.XX, replaces new line with space
loadAverages="$(uptime | grep -o [0-9][.][0-9][0-9] | tr '\n' ' ')"
#runs free to show memory allocation on a new line
memAllocate="$(echo '' ; free)"
#runs ss looking for listening ports, extract all lines with 'LISTEN' after starting a new line
listenPorts="$(echo '' ; sudo ss -lntu | grep LISTEN)"
#runs ufw to get status of rules
ufwStstus="$(sudo ufw status numbered)"
#runs lshw looking for disk drives, extracts lines with 'product' and 'vendor', removes unimportant spaces, replaces 'product' and 'vendor' strings, removes new lines
listDisk="$(sudo lshw -c disk | grep -e 'product' -e 'vendor' | sed 's/       //' | sed 's/product/Disk Type/g' | sed 's/vendor/  Produced By/g' | tr -d '\n')"
#starts a new line, runs df in human-readable format
diskSpace="$(echo '' ; df -h)"

#########################################

#Report template
cat <<EOF

System Report generated by $myUsername, $currentDateTime
 
System Information
------------------
Hostname: $currentHostname
OS: $PRETTY_NAME
Uptime: $currentUptime
 
Hardware Information
--------------------
cpu: $cpuInfo
Speed: $cpuSpeed MHz
Ram: $ram
Disk(s): $listDisk
Video Card: $videoCard
 
Network Information
-------------------
FQDN: $getFQDN
Host Address: $hostnameIP
Gateway IP: $defaultGateway
DNS Server: $dnsIP
 
NIC: $nicInfo
IP Address: $cidrIP
 
System Status
-------------
Users Logged In: $usersLoggedIn
Disk Space: $diskSpace
Process Count: $processNum
Load Averages: $loadAverages
Memory Allocation: $memAllocate
Listening Network Ports: $listenPorts
UFW Rules: $ufwStatus
EOF
